name: Notify Discord on GitHub Events

on:
  push:
  pull_request:
  issues:
  issue_comment:
  fork:
  create:
  delete:
  release:
  # Add any other events you want to track

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"username": "GitHub Actions", "content": "Something happened in GitHub!"}' \
               "$DISCORD_WEBHOOK"
