name: Notify Discord on GitHub Events

on:
  push:
  pull_request:
  issues:
  issue_comment:
  fork:
  create:
  delete:
  release:
  workflow_dispatch: # Allows manual triggering

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_ACTION_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          MESSAGE="🔔 **GitHub Event Triggered!**\n
          📢 **Event:** $GITHUB_EVENT_NAME\n
          👤 **Triggered by:** $GITHUB_ACTOR\n
          📂 **Repository:** $GITHUB_REPO\n
          🔗 [View Workflow Run]($GITHUB_ACTION_URL)"
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\": \"GitHub Actions\", \"content\": \"$MESSAGE\"}" \
               "$DISCORD_WEBHOOK"
